services:
  db:
    image: postgres:15-alpine
    container_name: terminator_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: terminator_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
    # PARTIE 1 : LE HEALTHCHECK, QUI VÉRIFIE QUE LA BDD EST PRÊTE
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d terminator_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: terminator_api
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://user:password@db:5432/terminator_db
      - SECRET_KEY=une_super_cle_secrete_pour_le_dev
      
    # PARTIE 2 : LA CONDITION D'ATTENTE, QUI UTILISE LE HEALTHCHECK
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: