services:
  db:
    image: postgres:15-alpine
    container_name: terminator_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: terminator_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d terminator_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: terminator_api
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://user:password@db:5432/terminator_db
      - JWT_SECRET_KEY=une-cle-secrete-tres-longue-et-difficile-a-deviner
      # NOUVELLE VARIABLE : une liste d'origines autorisées, séparées par des virgules
      - CORS_ORIGINS=http://localhost:3000,http://192.168.1.56:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:

